name: Build and Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cxx: [g++-14, clang++-18]
        build_type: [Debug, Release]
        sanitizer: [address, others]
        include:
          - cxx: g++-14
            install: |
              sudo apt install g++-14
              sudo apt install libomp-18-dev mold ninja-build libmimalloc-dev libboost1.83-dev libbenchmark-dev libgtest-dev libre2-dev
          - cxx: clang++-18
            install: |
              sudo apt install clang++-18
              sudo apt install libomp-18-dev libc++-18-dev mold ninja-build libmimalloc-dev libboost1.83-dev libbenchmark-dev libgtest-dev libre2-dev

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        ${{ matrix.install }}

    - name: Configure
      env:
        CXX: ${{matrix.cxx}}
        CC: ${{ matrix.cxx == 'g++-14' && 'gcc-14' || 'clang-18' }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -Bbuild \
              -GNinja \
              -DEPOLL_WEB_ENABLE_STRICT_STL_CHECKS=ON \
              -DEPOLL_WEB_ENABLE_ADDRESS_SANITIZER=${{ matrix.sanitizer == 'address' && 'ON' || 'OFF' }} \
              -DEPOLL_WEB_ENABLE_UNDEFINED_SANITIZER=${{ matrix.sanitizer == 'others' && 'ON' || 'OFF' }} \
              -DEPOLL_WEB_ENABLE_THREAD_SANITIZER=${{ matrix.sanitizer == 'others' && 'ON' || 'OFF' }} \
              -DEPOLL_WEB_ENABLE_MOLD=ON \
              -DEPOLL_WEB_ENABLE_AVX2=ON \
              $GITHUB_WORKSPACE

    - name: Build
      run: |
        cmake --build build --config ${{matrix.build_type}} --parallel
